### ISSUE TITLE
BiocycToCSV: left_end_protein_feature and right_end_protein_feature

### ISSUE THREAD

**Issue by TheYavimayan** [coffeetocode/bioinfoscripts#2]
GOAL: The goal of these two columns is to determine whether a amino acid is within an experimentally determined region of interest. The xml will define left and right parameters that are either a single amino acid or a range that the amino acid may fall into. Thus, I am hoping there is a way to have the script determine whether the amino acid integer I input is either specifically noted in the xml or if it is in a range defined in the xml.

CURRENT ISSUE: Currently, the integers pulled from the xml are syntactically correct, but not the ones I want. I am hoping to be able to add a number in the GENEIDS.txt file corresponding to an amino acid detected as acetylated. 

In the case of the example "EXAMPLE-all-products-of-gene.xml", the left end integer (50) is being pulled from Line 173 ,while the right end integer (157) is being pulled from 174 . 
However, the amino acid I actually care about is at position 20. This data is at Line 220 and Line 221, where both values are 20. This indicates that the amino acid 20 has been experimentally determined as important.

![image](https://cloud.githubusercontent.com/assets/20687057/17186095/6a48d2ea-53f9-11e6-887d-f06e4da503f7.png)
I know it's technically meaningless, but it's the only way that I'm finding to really show the difference. The image shows the amino acid (20) I care about is in the red circle, but the integers the script is putting out, (50-157) is in the red box. These "Sequence Pfam Features" numbers don't really have any meaning for me.

The issue is coming from the fact the paths to these integers are identical:
/ptools-xml/Protein/has-feature/Feature/left-end-position
/ptools-xml/Protein/has-feature/Feature/right-end-position

SOLUTION?: Perhaps by defining my amino acid integer of interest (20) in the GENEIDS.txt in some way, or maybe by making the input a GENEIDS.CSV with the gene ID (EG10943) in column A and acetylation site (20) in column B, that might be more convenient (and easier with the data sets I have). 

Again, the left and right ends define a range, so when there is a single amino acid like the one at position 20, the left and right ends are identical. However, the xml may define a range like the incorrect left and right ends from 50-->157. My hope is that we can make the script determine whether the integer I input is contained in the left end, right end, or in between the ends.

**Comment by coffeetocode** [comment]
Okay, I think I got it. Lots going on with this so I had to wait until the weekend to read carefully. Can you include here a full GENEIDS.csv (drag/drop or copy/paste) with acytelation site? I'm hoping for like 4-5 examples that include each case of specific position (left & right are same; a range; range doesn't match site, etc)

Here's an example of the new GENEIDS.csv if you want to start with that (obviously acetylation_site is bogus for all but the first)
```
ecocyc_accession_id,acetylation_site,note
EG10943,20,
EG10020,20,
EG11647,20,
EG10217,20,
EG11528,20,
```

I've got most of the code changed, I just want to run the resulting output by you to see if I understood correctly.

**Comment by coffeetocode** [comment]
Oh, and I meant to ask; what's the intended output here? A new column like "features_at_acetylation_site" that identifies any feature(s) whose range spans (or matches) the acetylation_site provided in the CSV?

Thoughts on if there are none or more than one, or a range vs position?

**Comment by coffeetocode** [comment]
Aside from the ugly formatting of the new features_at_acetylation_site column (and the fact that the sites are still bogus data in GENEIDS.csv), I think you'll like this.

**Comment by TheYavimayan** [comment]
You are correct that I'd like this! It's exactly what I needed! I had one final change that I'd like to make, but I'll open a new issue that will probably be super easy to close.
