### ISSUE TITLE
BiocycToCSV: assay column

### ISSUE THREAD

**Issue by TheYavimayan** [coffeetocode/bioinfoscripts#3]
The output into the assay column only puts out one value, which is fine. However, there are many different assay parameters that share the same path.

This is taken from Line 439 in the Example-all-products-of-gene. While this is good in this example, there are other cases I have seen where taking the first instance of this path doesn't give me the information I need. The path to this data and other data, share the following:
/ptools-xml/Protein/has-go-term/evidence/Evidence-Code/common-name

I've change my mind about how I could utilize this column with the ability to automate this whole process. I think this could work best if we search all instances of this path, and make multiple "Assay" columns in the CSV: Direct assay, Purified assay, Mutant assay. These Assay columns would correspond to whether these paths contain the even one instance of the words "Direct", "Purified", and "Mutant", which correspond to the different methods I can use to determine the function of this protein. 

Thus, column H could be "Direct assay", and if script looks through all the "/ptools-xml/Protein/has-go-term/evidence/Evidence-Code/common-name" paths and one of them contains the word "Direct", that column would contain the text as the output is now.. If the script does not find the word "Direct", it could have the NaN as it does already for molecular weight. Then, the script could do the same with the words "Purified" and "Mutant". 

This is especially helpful because sometimes the "Assay" used is computational, which I cannot directly test and will not help me.

**Comment by coffeetocode** [comment]
Functionality is in, but I don't know if the data in the "common name" field is standardized enough to just grab a single word out of it (eg "mutant") and and be confident that the output has correctly captured the available evidence. So make sure to check that out, but that seems to work for the examples I currently have.

See exactly what it's doing at https://github.com/coffeetocode/bioinfoscripts/blob/master/BiocycToCSV/geneid_to_csv.py#L48 

If that'll work, lemme know and I'll close the issue.

**Comment by TheYavimayan** [comment]
Looking good to me! I just have one final thing I'd like changed that will be lumped in a new issue.
