### ISSUE TITLE
Error encountered with certain GENEIDs.

### ISSUE THREAD

**Issue by TheYavimayan** [coffeetocode/bioinfoscripts#5]
![image](https://cloud.githubusercontent.com/assets/20687057/17340894/bc7935ce-58b7-11e6-9bdf-9e4a91f626e7.png)

The script works so well, but I just hit a snag. There were two geneIDs that didn't work for some reason (error attached above).

These are EG10703, 27 and EG12144, 457. Not sure what is going wrong, but I bet it will be no trouble for you!

The CSV values are as follows:

ecocyc_accession_id,acetylation_site,note
EG10411,38,
EG10411,38,
EG11037,253,
EG11699,18,
EG11699,106,
EG10025,531,
EG10703,27,
EG12144,457,
EG10810,432,
EG10889,47,
EG10931,312,
G7087,33,
EG11490,3,

Thanks!

**Comment by coffeetocode** [comment]
For your edification, here's how to read/debug that.

It saves each xml into an xml_cache with a filename corresponding to the geneid, so you can go grab and open the failing XML from your local machine. The error message tells you that it's failing when it tries to read the gene name (./Protein/common-name is the xpath, where I'm already treating ptools-xml as the root). 

So you can open EG10703.xml, then see under ptoolsxml/Protein/ that there isn't a common name entry (compare to another file to see where it should be). Heh, and now we know something new about how this data is(n't) standardized :)

I'll add a commit to fix that, and you can take a look at the diff to see the change.

**Comment by TheYavimayan** [comment]
That makes sense. It seems to be working perfectly now. I'm doing the last two data sets now, so hopefully that's it!
